version: "3.8"
services:
  mc:
    build: .
    environment:
      EULA: "true"
    ports:
      - "25565:25565"
    volumes:
      - ./server:/server
    restart: unless-stopped
    # コンテナ内で開発するから落とさない
    tty: true
    stdin_open: true